# URL
title: 笔记本                        # 站点名
description: Sky's notebook           # 站点描述
url: https://note.zdl.im       # 域名
baseurl: /                    # 根目录

# 社交帐号
## 会在页面底部显示，建议挑 4 个
github: 
weibo:
telegram: qshare
zhihu: 
linkedin:
mail: aosky@zdl.im


# 站点资源
img: /assets/img          # 图片库
css: /assets/css          # CSS 样式库
js:  /assets/js           # js 库
cdn: https://cdn.jsdelivr.net/gh/aosky/wiki@gh-pages/assets/img # CDN 加速

# 背景图片
bg: home.jpg

# Jekyll 插件
## Docs: https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# 评论系统（本主题使用 gitalk）
## Docs: https://github.com/gitalk/gitalk/blob/master/readme-cn.md
gitalk:
  enable: false 
  clientID: 6e42adfac0bf61e180f6
  clientSecret: d1ed44fc8888bbb2bcafb6bbc819ac9dddca5b71
  repo: wiki
  owner: aosky
  admin: aosky
  id: simple      # 默认是 location.pathname
  title: simple   # issue 标题
  body: simple
  

# Google Analytics
## Docs: https://analytics.google.com/analytics/web/
google-analytics: UA-165708741-1

# 默认 _post 文件夹用 post 布局
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
